version: '3.1'
services:
  web:
    image: nginx
    container_name: vs_web
    restart: always
    ports:
      - 9988:8888
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./build:/usr/share/nginx/html
      - ./build:/value-seeker/build
